okta:
  oauth2:
    issuer: ${IDP_ISSUER}
    client-id: ${IDP_CLIENT_ID}
    client-secret: ${IDP_CLIENT_SECRET}

spring:
  application:
    name: myfinances-gateway
  session:
    store-type: redis
  data:
    redis:
      host: ${REDIS_URL}
  cloud:
    gateway:
      routes:
        - id: api
          uri: ${API_URL}
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
        - id: frontend
          uri: ${FRONTEND_URL}
          predicates:
            - Path=/app/**
        - id: root-redirect
          uri: http://localhost  # URI "falsa", será aplicado o redirect
          predicates:
            - Path=/
          filters:
            - RedirectTo=302, /app
# Actuator
management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: info,health

server:
  forward-headers-strategy: native
  reactive:
    session:
      timeout: 30d

#MONITORING
sentry:
  exception-resolver-order: -2147483647
  release: ${SOURCE_COMMIT:0.0.0}
  traces-sample-rate: 1.0
  send-default-pii: true